# Generated by Django 3.0.6 on 2021-04-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogofly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completion_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='welcome_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name="What's on your mind ?"),
        ),
    ]
