# Generated by Django 3.0.6 on 2021-05-21 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cogofly', '0002_auto_20210419_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='trip',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='cogofly.Trip'),
        ),
    ]
