# Generated by Django 3.0.6 on 2021-07-08 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cogofly', '0004_auto_20210625_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacy',
            name='about',
            field=models.IntegerField(choices=[(0, 'Nobody'), (1, 'Friends only'), (2, 'Everybody')], default=0, verbose_name='about you'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='children',
            field=models.IntegerField(choices=[(0, 'Nobody'), (1, 'Friends only'), (2, 'Everybody')], default=0, verbose_name='number of children'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='current',
            field=models.IntegerField(choices=[(0, 'Nobody'), (1, 'Friends only'), (2, 'Everybody')], default=0, verbose_name='current employer'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='level',
            field=models.IntegerField(choices=[(0, 'Nobody'), (1, 'Friends only'), (2, 'Everybody')], default=0, verbose_name='education level'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='previous',
            field=models.IntegerField(choices=[(0, 'Nobody'), (1, 'Friends only'), (2, 'Everybody')], default=0, verbose_name='previous employer'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='sector',
            field=models.IntegerField(choices=[(0, 'Nobody'), (1, 'Friends only'), (2, 'Everybody')], default=0, verbose_name='activity sector'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='subjects',
            field=models.IntegerField(choices=[(0, 'Nobody'), (1, 'Friends only'), (2, 'Everybody')], default=0, verbose_name='study subjects'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='zodiac',
            field=models.IntegerField(choices=[(0, 'Nobody'), (1, 'Friends only'), (2, 'Everybody')], default=0, verbose_name='star sign'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cogofly.City', verbose_name='birthplace'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='how',
            field=models.IntegerField(blank=True, choices=[(0, 'Facebook'), (1, 'Google'), (3, 'Twitter'), (4, 'Other social media'), (5, 'Flyers'), (6, 'Word of mouth')], null=True, verbose_name='how do you know CoGoFly?'),
        ),
        migrations.AlterField(
            model_name='search',
            name='children',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='number of children'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_frequency',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'Daily'), (2, 'Weekly'), (3, 'Monthly')], default=0, verbose_name='notification frequency'),
        ),
    ]
