# Generated by Django 3.0.6 on 2021-10-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogofly', '0005_auto_20210708_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='Return date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Departure date'),
        ),
    ]
