# Generated by Django 3.0.6 on 2021-10-30 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cogofly', '0006_auto_20211030_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
