# Generated by Django 3.0.6 on 2021-11-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cogofly', '0007_auto_20211030_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_country', to='cogofly.Country'),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_country', to='cogofly.Region'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='cogofly.City'),
        ),
    ]
