# Generated by Django 3.0.6 on 2022-03-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogofly', '0010_auto_20220328_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='I_have_an_handicap',
        ),
        migrations.AddField(
            model_name='privacy',
            name='handicap',
            field=models.BooleanField(default=False, verbose_name='handicap'),
        ),
        migrations.AddField(
            model_name='privacy',
            name='help_hukranians',
            field=models.BooleanField(default=False, verbose_name='help hukranians'),
        ),
        migrations.AddField(
            model_name='search',
            name='handicap',
            field=models.BooleanField(default=False, verbose_name='handicap'),
        ),
        migrations.AlterField(
            model_name='search',
            name='help_ukranian',
            field=models.BooleanField(default=False, verbose_name='Help ukranian'),
        ),
    ]
