# Generated by Django 3.0.6 on 2022-03-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogofly', '0012_auto_20220331_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacy',
            name='handicap',
            field=models.IntegerField(choices=[(0, 'Nobody'), (1, 'Friends only'), (2, 'Everybody')], default=0, verbose_name='handicap'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='help_hukranian',
            field=models.IntegerField(choices=[(0, 'Nobody'), (1, 'Friends only'), (2, 'Everybody')], default=0, verbose_name='help hukranian'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='handicap',
            field=models.BooleanField(default=False, null=True, verbose_name='I have a handicap'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='help_ukranian',
            field=models.BooleanField(default=False, null=True, verbose_name='Help Ukranian'),
        ),
    ]
