# Generated by Django 3.0.6 on 2022-04-01 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogofly', '0013_auto_20220331_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creation_account',
            field=models.DateField(default=datetime.date(2022, 4, 1)),
        ),
    ]
