# Generated by Django 3.0.6 on 2022-04-02 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogofly', '0014_user_creation_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_account',
            field=models.DateField(default=datetime.date(2022, 4, 2)),
        ),
    ]
