# Generated by Django 3.0.6 on 2022-04-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogofly', '0015_auto_20220402_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='is complete'),
        ),
    ]
