# Generated by Django 3.0.6 on 2022-04-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogofly', '0016_profile_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='is completed'),
        ),
    ]
