# Generated by Django 3.0.6 on 2022-04-02 08:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cogofly', '0017_auto_20220402_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 8, 8, 12, 619851, tzinfo=utc), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_account',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 8, 8, 12, 619851, tzinfo=utc)),
        ),
    ]
