# Generated by Django 3.0.6 on 2022-04-02 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cogofly', '0018_auto_20220402_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='creation_account',
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 8, 19, 2, 989606, tzinfo=utc)),
        ),
    ]
