# Generated by Django 3.0.6 on 2022-04-02 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cogofly', '0019_auto_20220402_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 8, 36, 13, 429798, tzinfo=utc)),
        ),
    ]
