# Generated by Django 3.0.6 on 2022-04-02 08:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cogofly', '0020_auto_20220402_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 8, 46, 47, 255492, tzinfo=utc)),
        ),
    ]
