# Generated by Django 3.0.6 on 2022-04-02 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogofly', '0022_auto_20220402_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateField(default=datetime.date(2022, 4, 2)),
        ),
    ]
