# Generated by Django 3.0.6 on 2022-04-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogofly', '0023_auto_20220402_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
