# Generated by Django 3.0.6 on 2022-04-01 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2022, 4, 1))),
                ('users_aountcreation', models.IntegerField(default=0)),
                ('users_profils_acount', models.IntegerField(default=0)),
                ('completed_users_profils_count', models.IntegerField(default=0)),
                ('users_messages_count', models.IntegerField(default=0)),
                ('users_connected_count', models.IntegerField(default=0)),
                ('users_guest_count', models.IntegerField(default=0)),
                ('users_profils_count_by_profil_hadicap', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PageNbVisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('nb_visites', models.IntegerField(default=1)),
                ('creation_date', models.DateTimeField(default=datetime.date(2022, 4, 1))),
            ],
        ),
    ]
