# Generated by Django 3.0.6 on 2022-04-02 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_auto_20220402_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstatus',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 7, 43, 43, 351428, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pagenbvisites',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 7, 43, 43, 351428, tzinfo=utc)),
        ),
    ]
