# Generated by Django 3.0.6 on 2022-04-02 08:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_auto_20220402_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstatus',
            name='daily_trips_added',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appstatus',
            name='total_trips_added',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appstatus',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 8, 8, 12, 635473, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pagenbvisites',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 8, 8, 12, 635473, tzinfo=utc)),
        ),
    ]
