# Generated by Django 3.0.6 on 2022-04-02 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0006_auto_20220402_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagenbvisites',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='appstatus',
            name='daily_searches_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appstatus',
            name='pictures_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appstatus',
            name='total_searches_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagenbvisites',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 8, 19, 3, 5229, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appstatus',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 8, 19, 3, 5229, tzinfo=utc)),
        ),
    ]
