# Generated by Django 3.0.6 on 2022-04-02 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0007_auto_20220402_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstatus',
            name='counter_nb_visites_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appstatus',
            name='counter_nb_visites_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appstatus',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 8, 36, 13, 445420, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pagenbvisites',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 8, 36, 13, 445420, tzinfo=utc)),
        ),
    ]
