# Generated by Django 3.0.6 on 2022-04-02 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0011_auto_20220402_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstatus',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 9, 9, 39, 241715, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pagenbvisites',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 9, 9, 39, 241715, tzinfo=utc)),
        ),
    ]
