# Generated by Django 3.0.6 on 2022-10-24 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0013_auto_20220708_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstatus',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 24, 7, 21, 4, 557625, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pagenbvisites',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 7, 21, 4, 557625, tzinfo=utc)),
        ),
    ]
